### ISSUE TITLE
Write the A*

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/graph-algorithms#13]
We have this implementation that is the implementation of the pseudocode of wikipedia

https://github.com/tatut/aoc2021-smalltalk/blob/main/src/AoC2021/AStar.class.st

**Comment by virenvarma007** [comment]
Hello @jordanmontt 
I had adding A* Algorithm to the library as deliverable in my gsoc proposal. I'll be taking up this issue

**Comment by jordanmontt** [comment]
Implemented on #23
