### ISSUE TITLE
Cleanup: "AI-Algorithms-Graph" package contains untagged classes

### ISSUE THREAD

**Issue by astares** [pharo-ai/graph-algorithms#34]
see https://github.com/pharo-project/pharo/issues/15482 which needs to be fixed in 
original https://github.com/pharo-ai/graph-algorithms repo

**Comment by jordanmontt** [comment]
Fixed in
- https://github.com/pharo-ai/graph-algorithms/pull/38
- https://github.com/pharo-ai/graph-algorithms/pull/36
