### ISSUE TITLE
Use a heap as a data structure in Dijkstra's algo instead of a OrderedCollection for the priority queue

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/graph-algorithms#5]
The ordered collection is the naive implementation of the priority queue. We should use other data structure to improve the time complexity of our implementation of Dijkstra

**Comment by nikhil061102** [comment]
I think we can discuss and solve this problem. By the way, I am new to open source contributions so this will be a good start for me :)

**Comment by jordanmontt** [comment]
Yes, it would be really cool :)
The idea of this issue is to develop the heap, or priority queue data structure. It is not an easy tasks. If you have ideas or experience on how to do it please share them

**Comment by Ducasse** [comment]
I think that there is already a Heap Datastructure in Pharo.

**Comment by jordanmontt** [comment]
Fixed in #f8c72fcc209dd9f4e0683b89fc49e6896e8d50cd
